image: golang:latest

before_script:
# Load private key
- which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
- eval $(ssh-agent -s)
- ssh-add <(echo "$SSH_PRIVATE_KEY")
- mkdir -p ~/.ssh

deploy:
  stage: deploy
  only:
  - master
  script:
  # Build project
  - go build
  # Kill the bot
  - ssh -o StrictHostKeyChecking=no gitlabci@$SSH_IP 'killall -s SIGINT TypedGit || true'
  - ssh -o StrictHostKeyChecking=no gitlabci@$SSH_IP 'screen -S TypedGit -X quit || true'
  # Push to server
  - scp -o StrictHostKeyChecking=no ./soulbot gitlabci@$SSH_IP:/home/gitlabci/typedgit/TypedGit
  # Start the bot
  - ssh -o StrictHostKeyChecking=no gitlabci@$SSH_IP 'screen -dmS TypedGit sh'
  - ssh -o StrictHostKeyChecking=no gitlabci@$SSH_IP 'screen -S TypedGit -X stuff "cd /home/gitlabci/typedgit\n"'
  - ssh -o StrictHostKeyChecking=no gitlabci@$SSH_IP 'screen -S TypedGit -X stuff "./TypedGit\n"'
